# setup.py
from setuptools import setup, find_packages

setup(
    name='my-awesome-package',
    version='0.1.0',
    author='Your Name',
    author_email='your.email@example.com',
    description='A short description of my awesome package.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/my-awesome-package',
    packages=find_packages(), # This automatically finds your Python packages
    install_requires=[
        'requests>=2.20.0',
        'numpy',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7',
)